---
title: "Bar Chart / Aggregation"
output: html_notebook
---

Start by getting the data

```{r}

# Get Google Analytics credentials and set them. 
ga_client_id <- Sys.getenv("GA_CLIENT_ID")
ga_client_secret <- Sys.getenv("GA_CLIENT_SECRET")

options(googleAuthR.client_id = ga_client_id)
options(googleAuthR.client_secret = ga_client_secret) 

packages <- c("tidyverse","googleAnalyticsR", "splitstackshape", "knitr", "kableExtra", "extrafont")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}

library(tidyverse)
library(googleAnalyticsR)
library(splitstackshape)
library(knitr)
library(kableExtra)
library(extrafont)

end_date <- as.Date("2017-10-30")
start_date <- as.Date("2017-10-01")

date_range <- c(start_date, end_date)

# Authorize Google Analytics
ga_auth()

view_id <- Sys.getenv("GA_VIEW_ID_TRAINING")

# Pull the data
ga_data_original <- google_analytics_4(view_id,
                              date_range = date_range,
                              metrics = "sessions",
                              dimensions = "channelGrouping",
                              order = order_type("sessions",
                                                 sort_order = "ASCENDING",
                                                 orderType = "VALUE"))

# 'Digital Display' is a junk/noise channel, so remove that. And
# go ahead and divide the numbers by 10 to make them smaller
ga_data_original <- ga_data_original %>% 
  filter(channelGrouping != "Digital Display") %>% 
  mutate(sessions = round(sessions/10))

# Now... we're going to make our example (but we really want to keep
# that original data, as we'll still need it).
ga_data <-  ga_data_original

# We want the bar chart to be ordered, so make channelGrouping a factor
ga_data$channelGrouping <- factor(ga_data$channelGrouping,
                                  levels = ga_data$channelGrouping)

# Convert the data into individual observations. expandRows takes the number of 
# sessions and duplicates the rows that many times
ga_data <- ga_data %>% 
  expandRows("sessions")

# channelGrouping is a factor, so we can put the y position for the
# dot as the numeric of the channelGrouping factor. We're going to do a 
# coord_flip, so this will get set as "x" but is, in actuality, the
# y position.
ga_data$y_pos <- as.numeric(ga_data$channelGrouping)

# Want to go +/- 0.4 randomly from the center of the bar
ga_data$y_offset <- runif(nrow(ga_data), min=-0.4, max=0.4)

# Calculate the final y position
ga_data$y_plot <- ga_data$y_pos + ga_data$y_offset

# Now, we want to vary along the x-axis within the bar, too. We 
# need to get a max for each bar, which is the number of sessions
# for each channel
ga_data_totals <- ga_data %>% 
  group_by(channelGrouping) %>% 
  summarise(channelTotal = n())

# Add those totals back into the overall data
ga_data <- ga_data %>% 
  left_join(ga_data_totals) 

ga_data$plot_sessions <- sapply(ga_data$channelTotal, 
                                function(x) round(runif(1, min = 25, max = x - 25),0))
```

Plot the data

```{r base_plot}
# Plot it!

# Themes are defined externally
source("scripts/themes_ref.R")

# We need the bar labels to show up, so need to calculate the x-axis limits
x_lims <-  c(0, max(ga_data_original$sessions) * 1.35)

# JUST the bar chart
gg1 <- ggplot(ga_data, mapping = aes(x = channelGrouping)) +
  geom_bar(fill = "#19a2b0", colour = "#19a2b0") +
  geom_text(data = ga_data_original, mapping = aes(x=channelGrouping, y=sessions + 1500, 
                                                   label=format(sessions, big.mark = ",")), size = 6, 
            hjust = 0, colour = "gray30") +
  scale_y_continuous(expand = c(0, 0), limits = x_lims) +
  coord_flip() +
  theme_bar

# Plot it
gg1

```

Faux underlying data:

```{r faux_detail}

# Show the (faux) underlying data
ga_data_formatted <- ga_data_original %>% 
  arrange(-sessions) %>% 
  mutate(sessions = format(sessions, big.mark=","))

names(ga_data_formatted) <- c("Channel", "Sessions")

kable(ga_data_formatted, row.names = FALSE, format = "html", align=c("l","r")) %>% 
  kable_styling(bootstrap_options = c("striped","condensed"), full_width = FALSE)

```

And now... the detailed data

```{r echo=FALSE}

# We don't want TOO many points to illustrate the point
ga_data_sample <- sample_n(ga_data, 5000)

# The bar chart with individual points
gg2 <- gg1 +
  geom_point(mapping = aes(x = y_plot, y = plot_sessions), 
             data = ga_data_sample,
             size = 0.4, colour = "#333333", alpha = 0.7)

gg2

```

And...a faux view of the underlying data

```{r fig.width=4.25, fig.height=5.5,echo=FALSE}

# The number of rows of faux data
num_rows <- 150

# Display the first part of the underlying data...sort of. We're going to fake it for this.
# Start by grabbing X random rows.
gg2_data <- ga_data %>% 
  sample_n(num_rows) %>% 
  select(channelGrouping)

# Function to generate faux IDs
gen_ids <- function(channel_grouping){
  id_parts <- runif(2, min=1000000000, max=9999999999)
  id_parts <- round(id_parts,0)
  faux_id <- paste0(id_parts, collapse = ".")
}

# Generate faux IDs
faux_ids <- sapply(gg2_data$channelGrouping, gen_ids)

# Put those faux ids into the faux data data frame
gg2_data$visit_id <- faux_ids

# Reorder the columns and just grab the top n
gg2_data <- gg2_data %>% 
  select(visit_id, channelGrouping) %>% 
  top_n(15)

kable(gg2_data, row.name=FALSE, format = "html") %>% 
  kable_styling(bootstrap_options = c("striped","condensed"), full_width = FALSE)

```

And... show with dummy variables

```{r echo=FALSE,fig.width=4.25, fig.height=5.5}

# Add a column with "1" for every cell, and then spread
# to get dummy variables created
gg2_data_dummies <- gg2_data %>% 
  mutate(flag = 1) %>% 
  spread(channelGrouping, flag)

# Flip all the NAs to be 0s
gg2_data_dummies[is.na(gg2_data_dummies)] <- 0

kable(gg2_data_dummies, row.name=FALSE, format = "html") %>% 
  kable_styling(bootstrap_options = c("striped","condensed"), full_width = FALSE)


```
