---
title: "Multiple Sites: Daily Trends by Channel"
output: html_notebook
---

This simply cycles through a slew of views and pulls daily data by channel.

**Note:** The one-time prep required to get this notebook to run is detailed at http://www.dartistics.com/googleanalytics/setup.html.

```{r setup, echo=FALSE, message=FALSE, results='hide'}

# Get Google Analytics credentials and set them. 
ga_client_id <- Sys.getenv("GA_CLIENT_ID")
ga_client_secret <- Sys.getenv("GA_CLIENT_SECRET")

options(googleAuthR.client_id = ga_client_id)
options(googleAuthR.client_secret = ga_client_secret) 

library(tidyverse)
library(googleAnalyticsR)
library(tools)
library(knitr)
library(kableExtra)
library(scales)

# Authorize Google Analytics
ga_auth()

view_ids <- list(CK = "109156790",
                 RF = "77791007",
                 BW3 = "4562532",
                 APT = "94317304",
                 CFA = "41367227",
                 LOL = "33153007",
                 SDI = "142910707")

# This was initially built to look at one month at a time, but, for the purposes of this
# analysis, we can just look at one 3-month timeframe. Change the start/end dates to
# inspect others.

date_ranges <- list(July = as.Date(c("2017-07-01","2017-07-31")),
                    August = as.Date(c("2017-08-01","2017-08-31")),
                    September = as.Date(c("2017-09-01","2017-09-30")),
                    October = as.Date(c("2017-10-01","2017-10-31")),
                    November = as.Date(c("2017-11-01","2017-11-30")),
                    December = as.Date(c("2017-12-01","2017-12-31")))
# 
# date_ranges <- list(May = as.Date(c("2017-05-01","2017-05-31")),
#                     June = as.Date(c("2017-06-01","2017-06-30")))
# 
# date_ranges <- list(Jul_Sep_2017 = as.Date(c("2017-07-01","2017-09-30")))

##############
# Function that pulls the data and generates the visualizations
##############

# Define the theme for the charts -- no need to keep re-defining every time the
# function runs, so defining it outside the function for use within the function.
theme_line <- 
  theme_bw() +
  theme(plot.title = element_text(size = 9, face = "bold", hjust = 0.5),
        plot.margin = margin(1.5,0,0,0,"cm"),
        axis.text.y = element_text(size = 8, margin = margin(l=0.5, unit="cm")),
        axis.text.x = element_text(size = 8, color = "gray60"),
        axis.ticks = element_blank(),
        axis.line.x = element_line(),
        axis.line.y = element_blank(),
        axis.title = element_text(size = 8, face = "bold"),
        axis.title.y = element_text(size = 8),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.position = "top",
        legend.justification = "center",
        panel.border = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(size=0.5, colour = "gray90"),
        panel.grid.minor = element_blank(),
        legend.text = element_text(size=8))

process_view_month <- function(site_name, view_id, date_range){
  
  # Pull the data we'll use and set up the basis for the different visualizations. Go ahead
  # and make both sets of results in title case.
  ga_all <- google_analytics_4(view_id,
                               date_range = date_range,
                               metrics = "sessions",
                               dimensions = c("date","channelGrouping","deviceCategory"),
                               anti_sample = TRUE) %>%
    mutate(deviceCategory = toTitleCase(deviceCategory),
           channelGrouping = toTitleCase(channelGrouping))
  
  # Remove "(Other)" just on principle and "Email" because it spikes
  ga_all <- ga_all %>%
    filter(channelGrouping != "(Other)", channelGrouping != "Email")
  
  # Calculate the total.
  ga_total <- sum(ga_all$sessions)
  
  # Roll up to just channel daily data (remove deviceGrouping). Go ahead and
  # get zeros in for any day that a channel has no data by spreading and 
  # then gathering
  ga_channel_day <- ga_all %>% 
    group_by(date,channelGrouping) %>% 
    summarise(sessions = sum(sessions)) %>% 
    spread(channelGrouping, sessions, fill = 0) %>% 
    gather(channelGrouping, sessions, -date)
  
  # Create the chart title (for the first chart)
  chart_title <- paste0(site_name," (", view_id, ")\nDate Range: ",
                       as.Date(date_range[1]), " to ", as.Date(date_range[2]))
  
  #############
  # Trend by Channel
  #############
  
  # Make a line chart for all of the channels
  gg_line_all <- ggplot(ga_channel_day, aes(x=date, y=sessions)) +
    geom_line(size = 0.7, mapping = aes(colour = channelGrouping)) +
    scale_y_continuous(expand = c(0,0), limits = c(0, max(ga_channel_day$sessions) +100 ), 
                       label = comma) +
    labs(x="", y = "Sessions", title = chart_title) +
    guides(colour=guide_legend(nrow=1)) +
    theme_line
}

##############
# Function that, for a given view, runs all of the date ranges
##############

process_view <- function(site_name, view_id){
  
  # Make a vector that repeats the view ID once for each date range
  site_name_rep <- rep(site_name, length(date_ranges))
  view_id_rep <- rep(view_id, length(date_ranges))
  
  # Process the various date ranges
  results <- pmap(list(site_name_rep, view_id_rep, date_ranges), process_view_month)
  
}

```

Actually process the list with the function. This returns a list of plots that then get output.

```{r run_results, echo=FALSE, message=FALSE, results='hide', fig.keep='all', fig.height=6}

# Process the view IDs
full_results <- map2(names(view_ids), view_ids, process_view) %>% flatten()

# Output the list
full_results

```
