---
title: "Pre-/Post-Analysis"
output: html_notebook
---

Show examples of how we expect data to look and how it winds up looking

```{r echo = FALSE}

if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse,
               scales,
               lubridate)

start_date <- Sys.Date() - 90 - 1
end_date <- Sys.Date() - 15 - 1
event_date <- Sys.Date() - 45 - 1

num_rows <- as.numeric(end_date - start_date + 1, units = "days")
base_mean <- 1200
low_change <- 200
high_change <- 500

set.seed(6170)

theme_main <-  theme_minimal() +
  theme(text = element_text("Lato"),
        axis.title = element_blank(),
        axis.line.y = element_blank(),
        axis.line.x = element_line(color = "gray60"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())


# Generate Data
df <- tibble(date = seq(start_date, end_date, by = 1)) 

# Add a low-variance and high-variance base series
df$low_var <- rnorm(num_rows, mean = base_mean, sd = 40) %>% round(0)
df$high_var <- rnorm(num_rows, mean = base_mean, sd = 250) %>% round(0)

# Make different versions
df <- df %>% 
  mutate(low_var_low_chg = ifelse(date <= event_date, low_var, low_var + low_change),
         low_var_high_chg = ifelse(date <= event_date, low_var, low_var + high_change),
         high_var_low_chg = ifelse(date <= event_date, high_var, high_var + low_change),
         high_var_high_chg = ifelse(date <= event_date, high_var, high_var + high_change),
         test_pre = ifelse(date <= event_date, high_var, NA),
         test_control = ifelse(date <= event_date, NA, high_var/2),
         test_challenge = ifelse(date <= event_date, NA, high_var/2 + high_change/2))

# Adjust the test/control a bit. We're just going to add the 
# value to one and subtract from the other to make them look a little better
test_adjust <- runif(num_rows, -50, 50) %>% round(0)
df$test_control <- df$test_control + test_adjust
df$test_challenge <- df$test_challenge - test_adjust

mean_control <- mean(df$test_control, na.rm = TRUE) %>% round(0)
mean_challenge <- mean(df$test_challenge, na.rm = TRUE) %>% round(0)

# Get the means added
df <- df %>% 
  mutate(test_control_mean = ifelse(date <= event_date, NA, mean_control),
         test_challenge_mean = ifelse(date <= event_date, NA, mean_challenge))


# Make a long version
df_long <- df %>% 
  select(-low_var, -high_var) %>%  # These are just the "base" values
  pivot_longer(-date, names_to = "series", values_to = "value")


```

Make the plots

```{r line_plots, fig.height = 1.25, fig.width = 3, echo = FALSE}

get_plot <- function(df = df_long, series_filter = "low_var_low_chg", 
                     y_max = max(df_long$value, na.rm = TRUE) + 10){
  
  df <- df %>% filter(series == series_filter)
  
  gg <- ggplot(df, aes(x = date, y = value, group = 1)) +
    geom_vline(aes(xintercept = event_date), linetype = "dashed", color = "#EF7D22", size = 0.8) +
    geom_line(size = 0.6, color = "#009CAB") +
    geom_text(data = tibble(x = event_date + 1, y = 350, label = "New Feature Rolled Out"),
              mapping = aes(x = x, y = y, label = label), family = "Lato", hjust = 0, color = "#EF7D22") + 
    scale_y_continuous(expand = c(0,0), limits = c(0, y_max), labels = comma) +
    theme_main
  
  gg
  
}

get_plot(df_long, "low_var_high_chg")
get_plot(df_long, "low_var_low_chg")
get_plot(df_long, "high_var_high_chg")
get_plot(df_long, "high_var_low_chg")
get_plot(df_long, "test_pre")

# Plotting the test is going to be a bit different
df_test <- df_long %>% filter(grepl("test", series))

gg <- ggplot(df_test, aes(x = date, y = value, color = series, linetype = series, size = series)) +
  geom_vline(aes(xintercept = event_date), linetype = "dashed", color = "#EF7D22", size = 0.8) +
  geom_line() +
  geom_text(data = tibble(x = event_date + 1, y = 350, label = "New Feature Rolled Out",
                          series = NA),
            mapping = aes(x = x, y = y, label = label), family = "Lato", hjust = 0, color = "#EF7D22") +
  scale_y_continuous(expand = c(0,0), limits = c(0, max(df_long$value, na.rm = TRUE) + 10), labels = comma) +
  scale_color_manual(values = c("#E66420", "gray60", "#004D53", "gray60", "#009CAB")) +
  scale_linetype_manual(values = c("solid", "dashed", "solid", "dashed", "solid")) +
  scale_size_manual(values = c(0.6, 0.4, 0.6, 0.4, 0.6)) +
  theme_main +
  theme(legend.position = "none")

gg

```
